[FIX] : pre-commit hook error output

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -2,6 +2,6 @@
 
 npm run doc
 if (( $? != 0 )); then
-	echo "Documentation generation failed, commit aborted." 2> /dev/null
+	echo "Documentation generation failed, commit aborted." >&2 /dev/null
 	exit 1
 fi
